// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL8z4VSeeeOtAvV6SaVRp3MybLAoyFEFg',
    appId: '1:166202283309:web:a40550c217edfc29ae6fa4',
    messagingSenderId: '166202283309',
    projectId: 'pizza-store-9f6ad',
    authDomain: 'pizza-store-9f6ad.firebaseapp.com',
    storageBucket: 'pizza-store-9f6ad.firebasestorage.app',
    measurementId: 'G-WPQG034NYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSv3Tp46AjDF2RcizRWRJfK8zmqHVnwr8',
    appId: '1:166202283309:android:746c1981af699048ae6fa4',
    messagingSenderId: '166202283309',
    projectId: 'pizza-store-9f6ad',
    storageBucket: 'pizza-store-9f6ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3GgHQO79msbFrFK5ntmA4iT8IPeKdbRo',
    appId: '1:166202283309:ios:4e033591738fdbb1ae6fa4',
    messagingSenderId: '166202283309',
    projectId: 'pizza-store-9f6ad',
    storageBucket: 'pizza-store-9f6ad.firebasestorage.app',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3GgHQO79msbFrFK5ntmA4iT8IPeKdbRo',
    appId: '1:166202283309:ios:4e033591738fdbb1ae6fa4',
    messagingSenderId: '166202283309',
    projectId: 'pizza-store-9f6ad',
    storageBucket: 'pizza-store-9f6ad.firebasestorage.app',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL8z4VSeeeOtAvV6SaVRp3MybLAoyFEFg',
    appId: '1:166202283309:web:d1c971ab44897aaeae6fa4',
    messagingSenderId: '166202283309',
    projectId: 'pizza-store-9f6ad',
    authDomain: 'pizza-store-9f6ad.firebaseapp.com',
    storageBucket: 'pizza-store-9f6ad.firebasestorage.app',
    measurementId: 'G-3FFLD2GTFG',
  );

}