// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr5styjP3-Qvty5-Vg_2HwogvwMD6xrW4',
    appId: '1:930666915254:web:087180fb67b4f09a8f0d17',
    messagingSenderId: '930666915254',
    projectId: 'foody-e611a',
    authDomain: 'foody-e611a.firebaseapp.com',
    storageBucket: 'foody-e611a.firebasestorage.app',
    measurementId: 'G-Q908V3133Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTkSkTzBvbJDmLcdCNwDUqz_0-eJh_aWA',
    appId: '1:930666915254:android:f569ef904ad5dd0f8f0d17',
    messagingSenderId: '930666915254',
    projectId: 'foody-e611a',
    storageBucket: 'foody-e611a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHjfaX6mbhOINpMMdPdG4-QQdfESrdw5Q',
    appId: '1:930666915254:ios:c930c4b7e4a4cbf58f0d17',
    messagingSenderId: '930666915254',
    projectId: 'foody-e611a',
    storageBucket: 'foody-e611a.firebasestorage.app',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHjfaX6mbhOINpMMdPdG4-QQdfESrdw5Q',
    appId: '1:930666915254:ios:c930c4b7e4a4cbf58f0d17',
    messagingSenderId: '930666915254',
    projectId: 'foody-e611a',
    storageBucket: 'foody-e611a.firebasestorage.app',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr5styjP3-Qvty5-Vg_2HwogvwMD6xrW4',
    appId: '1:930666915254:web:4ab77c24916f4ee18f0d17',
    messagingSenderId: '930666915254',
    projectId: 'foody-e611a',
    authDomain: 'foody-e611a.firebaseapp.com',
    storageBucket: 'foody-e611a.firebasestorage.app',
    measurementId: 'G-QZ63DJ9CHS',
  );

}